name: Star TV Link Guncelle

on:
  schedule:
    - cron: '0 * * * *' # Her saat başı çalışır
  workflow_dispatch: # Manuel çalıştırma butonu ekler

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Kodu cek
        uses: actions/checkout@v2

      - name: Python kur
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Tarayiciyi kur (Playwright)
        run: |
          pip install playwright
          playwright install chromium

      - name: Linki yakala
        run: python yakala.py

      - name: Degisiklikleri kaydet
        run: |
          git config --global user.name 'Github Bot'
          git config --global user.email 'bot@github.com'
          git add liste.m3u
          git commit -m "Link güncellendi" || exit 0
          git push
