name: Star TV Guncelle

on:
  schedule:
    - cron: '0 0 * * *' # Her gece 00:00
  workflow_dispatch: # Elle çalıştırma butonu

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Bu satır çok kritik, robotun yazma yetkisi
      
    steps:
      - name: Depoyu cek
        uses: actions/checkout@v4
        with:
          persist-credentials: false # Kendi tokenimizi kullanacağımız için bunu false yapıyoruz

      - name: Python kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Kutuphaneleri kur
        run: pip install requests

      - name: Linki yakala
        run: python yakala.py

      - name: Code 128'i Bitiren Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add liste.m3u
          git commit -m "Star TV linki tazelendi" || echo "Degisiklik yok"
          # Alttaki satır kapıyı zorla açar:
          git push "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" HEAD:main --force
