name: Star TV Guncelle

on:
  schedule:
    - cron: '0 0 * * *' # Her gece 00:00'da otomatik çalışır
  workflow_dispatch: # Actions sekmesinde "Run workflow" butonu çıkarır

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: # Code 128 hatasını önlemek için yazma izni
      contents: write
      
    steps:
      - name: Depoyu kopyala
        uses: actions/checkout@v4

      - name: Python ayarla
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Kutuphaneleri kur
        run: pip install requests

      - name: Linki yakala ve kaydet
        run: python yakala.py

      - name: Degisiklikleri depoya yukle
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add liste.m3u
          git commit -m "Otomatik Star TV guncellemesi" || echo "Degisiklik yok"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git commit -m "Otomatik Star TV guncellemesi" || echo "Degisiklik yok"
          git push origin HEAD:main

